sudo: required
services:
  - docker

before_install:
  - docker build -t alexskiffin/docker-react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alexskiffin/docker-react npm run test

after_success:
  - docker build -t alexskiffin/multi-client

# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-2"
#   app: "docker-react-test"
#   env: "DockerReactTest-env"
#   bucket_name: "elasticbeanstalk-us-east-2-810086262052"
#   bucket_path: "docker-react-test"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"