sudo: required
services:
  - docker

before_install:
  - docker build -t alexskiffin/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alexskiffin/multi-docker npm run test

after_success:
  - docker build -t alexskiffin/multi-client ./client
  - docker build -t alexskiffin/multi-nginx ./nginx
  - docker build -t alexskiffin/multi-server ./server
  - docker build -t alexskiffin/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push alexskiffin/multi-client
  - docker push alexskiffin/multi-nginx
  - docker push alexskiffin/multi-server
  - docker push alexskiffin/multi-worker